name: Convert and verify

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dmlex-v1-0:
    name: DMLex v1.0 OS
    uses: OASIS-Docs/publication-assurance/.github/workflows/convert-and-verify.yml@v1.12.0
    with:
      markdown: dmlex-v1.0/markdown
      schemas: dmlex-v1.0/specification/schemas
      docbook: dmlex-v1.0/specification
      profile: dmlex
      published-html: https://docs.oasis-open.org/lexidma/dmlex/v1.0/os/dmlex-v1.0-os.html
      published-pdf: https://docs.oasis-open.org/lexidma/dmlex/v1.0/os/dmlex-v1.0-os.pdf

  dmlex-v1-1-wd01:
    name: DMLex v1.1 WD01
    uses: OASIS-Docs/publication-assurance/.github/workflows/convert-and-verify.yml@v1.12.0
    with:
      markdown: dmlex-v1.1
      schemas: dmlex-v1.1/schemas
